config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :accreditation_school_lists
  resources :pmdk_school_lists
  resources :all_school_lists
  resources :address_kabupaten_lists
  resources :address_kecamatan_lists
  resources :address_province_lists
  resources :achievement_kategori_lists
  resources :achievement_tingkat_lists
  resources :source_motivation_lists
  resources :source_information_lists
  resources :batch_lists
  resources :organization_degree_lists
  resources :language_degree_lists
  resources :language_name_lists
  resources :extra_lists
  resources :personal_religion_lists
  resources :personal_gender_lists
  resources :parent_education_lists
  resources :parent_job_lists
  resources :high_school_majors
  resources :major_lists

  # get 'personals/new'
  # get 'personals/update'
  # get 'personals/edit'
  # get 'personals/show'
  # get 'personals/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  # delete user by its id
  delete 'users/:id', to: 'users#destroy', as: :delete_user
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # show all registered users
  # get '/users', to: 'users#index'
  # add REST resources for users
  resources :users
  # handling sessions
  get '/login', to: 'sessions#new' # login page
  post 'login', to: 'sessions#create' # create the session
  # delete the session
  delete '/logout', to: 'sessions#destroy' # delete the session
  resources :users do # add following and followers action
    member do # member: get the user id
      get :following, :followers # get the following and followers,
      # url: /users/1/following and /users/1/followers,
      # named following_user_path(1) and followers_user_path(1)
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # root "application#hello"
  # Defines the root path route ("/")
  # root "posts#index"
  # define as plural  if you have multiple data
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: %i[edit new update create]
  resources :microposts,            only: %i[create destroy]
  resources :relationships,         only: %i[create destroy]
  resources :personals,             only: %i[new create edit update show]
  resources :parents,               only: %i[new create edit update show]
  resources :addresses,             only: %i[new create edit update show]
  resources :languages,             only: %i[new create edit update show]
  resources :achievements,          only: %i[new create edit update show]
  resources :extras,                only: %i[new create edit update show]
  resources :organizations,         only: %i[new create edit update show]
  resources :sources,               only: %i[new create edit update show]
  resources :majors,                only: %i[new create edit update show]

  resources :pmdk_school_informations,      only: %i[new create edit update show]
  resources :pmdk_each_score_informations,  only: %i[new create edit update show]
  resources :pmdk_total_score_informations, only: %i[new create edit update show]

  resources :utbk_scores,                 only: %i[new create edit update show]
  resources :utbk_school_informations,    only: %i[new create edit update show]
  resources :usm_school_informations,     only: %i[new create edit update show]
end

app/models/major_list.rb
# frozen_string_literal: true

# model major_list : handle major_list
class MajorList < ApplicationRecord
  validates :jurusan, presence: true, length: { minimum: 4, maximum: 30 }, uniqueness: true
end

app/controllers/major_lists_controller.rb
# frozen_string_literal: true

# major list controller : handle major list
class MajorListsController < ApplicationController
  before_action :set_major_list, only: %i[show edit update destroy]
  before_action :admin_user, only: %i[create new edit update destroy]

  # GET /major_lists or /major_lists.json
  def index
    @major_lists = MajorList.all
  end

  # GET /major_lists/1 or /major_lists/1.json
  def show; end

  # GET /major_lists/new
  def new
    @major_list = MajorList.new
  end

  # GET /major_lists/1/edit
  def edit; end

  # POST /major_lists or /major_lists.json
  def create
    @major_list = MajorList.new(major_list_params)

    respond_to do |format|
      if @major_list.save
        format.html { redirect_to major_list_url(@major_list), notice: 'Major list was successfully created.' }
        format.json { render :show, status: :created, location: @major_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @major_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /major_lists/1 or /major_lists/1.json
  def update
    respond_to do |format|
      if @major_list.update(major_list_params)
        format.html { redirect_to major_list_url(@major_list), notice: 'Major list was successfully updated.' }
        format.json { render :show, status: :ok, location: @major_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @major_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /major_lists/1 or /major_lists/1.json
  def destroy
    @major_list.destroy!

    respond_to do |format|
      format.html { redirect_to major_lists_url, notice: 'Major list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_major_list
    @major_list = MajorList.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def major_list_params
    params.require(:major_list).permit(:jurusan)
  end
end

app/helpers/major_lists_helper.rb
# frozen_string_literal: true

module MajorListsHelper
end

app/views/major_lists/_form.html.erb
<%= form_with(model: major_list) do |form| %>
  <% if major_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(major_list.errors.count, "error") %> prohibited this major_list from being saved:</h2>

      <ul>
        <% major_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :jurusan, style: "display: block" %>
    <%= form.text_field :jurusan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/major_lists/_major_list.html.erb
<div id="<%= dom_id major_list %>">
  <p>
    <strong>Jurusan:</strong>
    <%= major_list.jurusan %>
  </p>

</div>

app/views/major_lists/edit.html.erb
<h1>Editing major list</h1>

<%= render "form", major_list: @major_list %>

<br>

<div>
  <%= link_to "Show this major list", @major_list %> |
  <%= link_to "Back to major lists", major_lists_path %>
</div>

app/views/major_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Major lists</h1>

<div id="major_lists">
  <% @major_lists.each do |major_list| %>
    <%= render major_list %>
    <p>
      <%= link_to "Show this major list", major_list %>
    </p>
  <% end %>
</div>

<%= link_to "New major list", new_major_list_path %>

app/views/major_lists/new.html.erb
<h1>New major list</h1>

<%= render "form", major_list: @major_list %>

<br>

<div>
  <%= link_to "Back to major lists", major_lists_path %>
</div>

app/views/major_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @major_list %>

<div>
  <%= link_to "Edit this major list", edit_major_list_path(@major_list) %> |
  <%= link_to "Back to major lists", major_lists_path %>

  <%= button_to "Destroy this major list", @major_list, method: :delete %>
</div>