config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :accreditation_school_lists
  resources :pmdk_school_lists
  resources :all_school_lists
  resources :address_kabupaten_lists
  resources :address_kecamatan_lists
  resources :address_province_lists
  resources :achievement_kategori_lists
  resources :achievement_tingkat_lists
  resources :source_motivation_lists
  resources :source_information_lists
  resources :batch_lists
  resources :organization_degree_lists
  resources :language_degree_lists
  resources :language_name_lists
  resources :extra_lists
  resources :personal_religion_lists
  resources :personal_gender_lists
  resources :parent_education_lists
  resources :parent_job_lists
  resources :high_school_majors
  resources :major_lists

  # get 'personals/new'
  # get 'personals/update'
  # get 'personals/edit'
  # get 'personals/show'
  # get 'personals/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  # delete user by its id
  delete 'users/:id', to: 'users#destroy', as: :delete_user
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # show all registered users
  # get '/users', to: 'users#index'
  # add REST resources for users
  resources :users
  # handling sessions
  get '/login', to: 'sessions#new' # login page
  post 'login', to: 'sessions#create' # create the session
  # delete the session
  delete '/logout', to: 'sessions#destroy' # delete the session
  resources :users do # add following and followers action
    member do # member: get the user id
      get :following, :followers # get the following and followers,
      # url: /users/1/following and /users/1/followers,
      # named following_user_path(1) and followers_user_path(1)
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # root "application#hello"
  # Defines the root path route ("/")
  # root "posts#index"
  # define as plural  if you have multiple data
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: %i[edit new update create]
  resources :microposts,            only: %i[create destroy]
  resources :relationships,         only: %i[create destroy]
  resources :personals,             only: %i[new create edit update show]
  resources :parents,               only: %i[new create edit update show]
  resources :addresses,             only: %i[new create edit update show]
  resources :languages,             only: %i[new create edit update show]
  resources :achievements,          only: %i[new create edit update show]
  resources :extras,                only: %i[new create edit update show]
  resources :organizations,         only: %i[new create edit update show]
  resources :sources,               only: %i[new create edit update show]
  resources :majors,                only: %i[new create edit update show]

  resources :pmdk_school_informations,      only: %i[new create edit update show]
  resources :pmdk_each_score_informations,  only: %i[new create edit update show]
  resources :pmdk_total_score_informations, only: %i[new create edit update show]

  resources :utbk_scores,                 only: %i[new create edit update show]
  resources :utbk_school_informations,    only: %i[new create edit update show]
  resources :usm_school_informations,     only: %i[new create edit update show]
end

app/models/language_degree_list.rb
# frozen_string_literal: true

# model language_degree_list : handle language_degree_list
class LanguageDegreeList < ApplicationRecord
  validates :tingkat, presence: true, length: { minimum: 4, maximum: 15 }
end

app/controllers/language_degree_lists_controller.rb
# frozen_string_literal: true

# language degree list controller : handle language degree list
class LanguageDegreeListsController < ApplicationController
  before_action :set_language_degree_list, only: %i[show edit update destroy]
  before_action :admin_user, only: %i[create new edit update destroy]

  # GET /language_degree_lists or /language_degree_lists.json
  def index
    @language_degree_lists = LanguageDegreeList.all
  end

  # GET /language_degree_lists/1 or /language_degree_lists/1.json
  def show; end

  # GET /language_degree_lists/new
  def new
    @language_degree_list = LanguageDegreeList.new
  end

  # GET /language_degree_lists/1/edit
  def edit; end

  # POST /language_degree_lists or /language_degree_lists.json
  def create
    @language_degree_list = LanguageDegreeList.new(language_degree_list_params)

    respond_to do |format|
      if @language_degree_list.save
        format.html do
          redirect_to language_degree_list_url(@language_degree_list),
                      notice: 'Language degree list was successfully created.'
        end
        format.json { render :show, status: :created, location: @language_degree_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language_degree_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /language_degree_lists/1 or /language_degree_lists/1.json
  def update
    respond_to do |format|
      if @language_degree_list.update(language_degree_list_params)
        format.html do
          redirect_to language_degree_list_url(@language_degree_list),
                      notice: 'Language degree list was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @language_degree_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language_degree_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /language_degree_lists/1 or /language_degree_lists/1.json
  def destroy
    @language_degree_list.destroy!

    respond_to do |format|
      format.html { redirect_to language_degree_lists_url, notice: 'Language degree list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_language_degree_list
    @language_degree_list = LanguageDegreeList.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def language_degree_list_params
    params.require(:language_degree_list).permit(:tingkat)
  end
end

app/helpers/language_degree_lists_helper.rb
# frozen_string_literal: true

module LanguageDegreeListsHelper
end

app/views/language_degree_lists/_form.html.erb
<%= form_with(model: language_degree_list) do |form| %>
  <% if language_degree_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(language_degree_list.errors.count, "error") %> prohibited this language_degree_list from being saved:</h2>

      <ul>
        <% language_degree_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tingkat, style: "display: block" %>
    <%= form.text_field :tingkat %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/language_degree_lists/_language_degree_list.html.erb
<div id="<%= dom_id language_degree_list %>">
  <p>
    <strong>Tingkat:</strong>
    <%= language_degree_list.tingkat %>
  </p>

</div>

app/views/language_degree_lists/edit.html.erb
<h1>Editing language degree list</h1>

<%= render "form", language_degree_list: @language_degree_list %>

<br>

<div>
  <%= link_to "Show this language degree list", @language_degree_list %> |
  <%= link_to "Back to language degree lists", language_degree_lists_path %>
</div>

app/views/language_degree_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Language degree lists</h1>

<div id="language_degree_lists">
  <% @language_degree_lists.each do |language_degree_list| %>
    <%= render language_degree_list %>
    <p>
      <%= link_to "Show this language degree list", language_degree_list %>
    </p>
  <% end %>
</div>

<%= link_to "New language degree list", new_language_degree_list_path %>

app/views/language_degree_lists/new.html.erb
<h1>New language degree list</h1>

<%= render "form", language_degree_list: @language_degree_list %>

<br>

<div>
  <%= link_to "Back to language degree lists", language_degree_lists_path %>
</div>

app/views/language_degree_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @language_degree_list %>

<div>
  <%= link_to "Edit this language degree list", edit_language_degree_list_path(@language_degree_list) %> |
  <%= link_to "Back to language degree lists", language_degree_lists_path %>

  <%= button_to "Destroy this language degree list", @language_degree_list, method: :delete %>
</div>